<?php

namespace Database\Seeders;

use Database\Seeders\Concerns\DisablesForeignKeys;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ComunicadosSeeder extends Seeder
{
    use DisablesForeignKeys;

    public function run(): void
    {
        $this->disableForeignKeys();
        DB::table('multimedia')->where('comunicado_id', '!=', null)->delete();
        DB::table('comunicados')->truncate();
        $this->enableForeignKeys();

        $comunicados = [
            [
                'titulo' => 'Convocatoria a Sesión Ordinaria del Concejo Municipal',
                'resumen' => 'Se convoca a todos los concejales a la sesión ordinaria programada para el próximo lunes a horas 9:00 en el salón de sesiones del Palacio Consistorial.',
                'cuerpo' => '<p>El Gobierno Autónomo Municipal de Achocalla convoca a los ciudadanos e instituciones a la sesión ordinaria del Concejo Municipal.</p><p>Orden del día: aprobación de presupuesto reformulado, tratamiento de proyectos de ley municipal y varios.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 120,
                'fecha_publicacion' => now()->subDays(2),
            ],
            [
                'titulo' => 'Inicio del Proyecto de Pavimentación Av. Principal Achocalla',
                'resumen' => 'La Alcaldía Municipal informa el inicio oficial de los trabajos de pavimentación de la Avenida Principal, beneficiando a más de 3.000 familias del municipio.',
                'cuerpo' => '<p>Con una inversión de Bs. 4.500.000 financiados con recursos propios y transferencias del TGN, se da inicio a la pavimentación de 2.8 km de la Avenida Principal.</p><p>Los trabajos se realizarán de lunes a sábado de 7:00 a 18:00. Se solicita a los vecinos respetar las señalizaciones de desvío.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 245,
                'fecha_publicacion' => now()->subDays(5),
            ],
            [
                'titulo' => 'Campaña de Vacunación Gratuita para Mascotas 2026',
                'resumen' => 'El GAMA en coordinación con el SEDES La Paz realizará la campaña anual de vacunación antirrábica gratuita para perros y gatos en todas las subalcaldías.',
                'cuerpo' => '<p>Fechas: 10 al 20 de abril de 2026. Lugares: plazas principales de cada comunidad.</p><p>Se vacunará gratuitamente contra la rabia, parvovirosis y moquillo. Traer al animal con correa o en caja transportadora.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 89,
                'fecha_publicacion' => now()->subDays(7),
            ],
            [
                'titulo' => 'Licitación Pública: Construcción de Cancha Deportiva en Villa Achocalla',
                'resumen' => 'Se convoca a empresas constructoras a presentar propuestas para la construcción de una cancha deportiva multifuncional con graderías en la comunidad Villa Achocalla.',
                'cuerpo' => '<p>Presupuesto referencial: Bs. 850.000. Plazo de ejecución: 120 días calendario.</p><p>Los pliegos de condiciones están disponibles en la Unidad de Contrataciones del GAMA, de lunes a viernes de 8:30 a 16:30.</p><p>Fecha límite de presentación de propuestas: 30 de abril de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 67,
                'fecha_publicacion' => now()->subDays(10),
            ],
            [
                'titulo' => 'Recordatorio: Pago de Impuesto a la Propiedad Inmueble 2026',
                'resumen' => 'El GAMA recuerda a los contribuyentes que el plazo para el pago del Impuesto a la Propiedad Inmueble con descuento del 20% vence el 31 de mayo de 2026.',
                'cuerpo' => '<p>Los contribuyentes pueden realizar el pago en la ventanilla de recaudaciones de la Alcaldía, de lunes a viernes de 8:30 a 16:00.</p><p>Descuentos: 20% hasta el 31 de mayo, 10% hasta el 30 de junio. Sin descuento del 1 de julio en adelante.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 310,
                'fecha_publicacion' => now()->subDays(14),
            ],
            [
                'titulo' => 'Apertura de Inscripciones: Talleres Municipales de Verano 2026',
                'resumen' => 'El GAMA abre inscripciones para los talleres municipales gratuitos de danza, pintura, música, deportes y computación dirigidos a niños y jóvenes del municipio.',
                'cuerpo' => '<p>Talleres disponibles: danza folclórica, pintura artística, guitarra, fútbol, básquet y computación básica.</p><p>Dirigido a: niños y jóvenes de 6 a 18 años, residentes del municipio de Achocalla.</p><p>Inscripciones: del 5 al 20 de abril en la Dirección de Cultura y Deportes del GAMA.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 178,
                'fecha_publicacion' => now()->subDays(18),
            ],
            [
                'titulo' => 'Suspensión Temporal de Servicios en Centro de Salud',
                'resumen' => 'El Centro de Salud Municipal permanecerá cerrado por mantenimiento el próximo fin de semana.',
                'cuerpo' => '<p>Debido a trabajos de mantenimiento eléctrico, el Centro de Salud Municipal estará cerrado desde el sábado 10 de abril hasta el lunes 12 de abril de 2026.</p><p>Los servicios de urgencia estarán disponibles en el Hospital de La Paz.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 95,
                'fecha_publicacion' => now()->subDays(20),
            ],
            [
                'titulo' => 'Feria Municipal de Artesanías y Productos Locales',
                'resumen' => 'Se invita a la población a participar en la Feria Municipal que se realizará este fin de semana en la plaza principal.',
                'cuerpo' => '<p>La feria contará con stands de artesanías, productos agrícolas y gastronómicos locales.</p><p>Horario: sábado y domingo de 9:00 a 18:00. Entrada libre.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 210,
                'fecha_publicacion' => now()->subDays(22),
            ],
            [
                'titulo' => 'Convocatoria para Voluntarios en Campaña de Reforestación',
                'resumen' => 'El GAMA busca voluntarios para participar en la campaña de reforestación programada para el mes próximo.',
                'cuerpo' => '<p>Fecha: 25 de abril de 2026. Lugar: Cerro Achocalla.</p><p>Se proporcionarán herramientas y refrigerios. Inscripciones en la Dirección de Medio Ambiente.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 145,
                'fecha_publicacion' => now()->subDays(25),
            ],
            [
                'titulo' => 'Actualización del Horario de Recolección de Basura',
                'resumen' => 'A partir de la próxima semana, el horario de recolección de basura en el centro urbano cambia.',
                'cuerpo' => '<p>Nuevo horario: lunes, miércoles y viernes de 6:00 a 8:00. Se solicita depositar la basura en bolsas cerradas.</p><p>Multas por incumplimiento: Bs. 50.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 320,
                'fecha_publicacion' => now()->subDays(28),
            ],
            [
                'titulo' => 'Inauguración de Nuevo Parque Infantil',
                'resumen' => 'El GAMA inaugura el nuevo parque infantil en la comunidad de Villa Nueva.',
                'cuerpo' => '<p>El parque cuenta con juegos infantiles, áreas verdes y bancas.</p><p>Inauguración: 15 de abril de 2026 a las 10:00. Invitados especiales: alcalde y concejales.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 280,
                'fecha_publicacion' => now()->subDays(30),
            ],
            [
                'titulo' => 'Curso Gratuito de Primeros Auxilios',
                'resumen' => 'La Dirección de Salud Municipal ofrece curso gratuito de primeros auxilios para la comunidad.',
                'cuerpo' => '<p>Fechas: 20 y 22 de abril de 2026. Lugar: Centro de Salud Municipal.</p><p>Dirigido a: adultos mayores y jóvenes. Cupos limitados.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 165,
                'fecha_publicacion' => now()->subDays(32),
            ],
            [
                'titulo' => 'Suspensión de Clases por Día del Trabajador',
                'resumen' => 'Las unidades educativas del municipio suspenderán clases el 1 de mayo de 2026.',
                'cuerpo' => '<p>En conmemoración del Día del Trabajador, no habrá clases en todas las unidades educativas fiscales y privadas.</p><p>Las clases se reanudan el martes 2 de mayo.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 400,
                'fecha_publicacion' => now()->subDays(35),
            ],
            [
                'titulo' => 'Licitación para Suministro de Materiales de Construcción',
                'resumen' => 'Se convoca a proveedores a participar en la licitación para suministro de materiales de construcción.',
                'cuerpo' => '<p>Presupuesto: Bs. 1.200.000. Fecha límite: 10 de mayo de 2026.</p><p>Información en la Unidad de Contrataciones del GAMA.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 85,
                'fecha_publicacion' => now()->subDays(38),
            ],
            [
                'titulo' => 'Campaña de Donación de Sangre',
                'resumen' => 'El Banco de Sangre Municipal realiza campaña de donación voluntaria.',
                'cuerpo' => '<p>Fecha: 5 de mayo de 2026. Lugar: Centro de Salud.</p><p>Requisitos: mayor de 18 años, peso mínimo 50 kg. Traer documento de identidad.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 195,
                'fecha_publicacion' => now()->subDays(40),
            ],
            [
                'titulo' => 'Mantenimiento de Redes Eléctricas en Zona Norte',
                'resumen' => 'Se informa sobre trabajos de mantenimiento en las redes eléctricas de la zona norte del municipio.',
                'cuerpo' => '<p>Fechas: 8 al 12 de mayo de 2026. Posibles interrupciones de servicio.</p><p>Se solicita comprensión de la población.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 110,
                'fecha_publicacion' => now()->subDays(42),
            ],
            [
                'titulo' => 'Festival Cultural Municipal 2026',
                'resumen' => 'El GAMA organiza el Festival Cultural Municipal con participación de artistas locales.',
                'cuerpo' => '<p>Fecha: 15 de mayo de 2026. Lugar: Plaza Principal.</p><p>Actividades: música, danza, teatro y gastronomía típica.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 350,
                'fecha_publicacion' => now()->subDays(45),
            ],
            [
                'titulo' => 'Programa de Apoyo a Emprendedores',
                'resumen' => 'Se lanza programa de apoyo económico para emprendedores del municipio.',
                'cuerpo' => '<p>Subvenciones de hasta Bs. 5.000 para proyectos productivos.</p><p>Inscripciones: hasta el 30 de mayo de 2026 en la Dirección de Desarrollo Económico.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 225,
                'fecha_publicacion' => now()->subDays(48),
            ],
            [
                'titulo' => 'Censo Poblacional 2026',
                'resumen' => 'El Gobierno Nacional realiza censo poblacional en todo el país.',
                'cuerpo' => '<p>Fecha: 15 de junio de 2026. Participación obligatoria.</p><p>Información en las subalcaldías y centros educativos.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 480,
                'fecha_publicacion' => now()->subDays(50),
            ],
            [
                'titulo' => 'Construcción de Puente Peatonal en Río Achocalla',
                'resumen' => 'Inicio de construcción de puente peatonal para mejorar la conectividad.',
                'cuerpo' => '<p>Inversión: Bs. 300.000. Plazo: 60 días.</p><p>Beneficiará a comunidades ribereñas.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 135,
                'fecha_publicacion' => now()->subDays(52),
            ],
            [
                'titulo' => 'Taller de Capacitación en Agricultura Sostenible',
                'resumen' => 'La Dirección de Desarrollo Rural ofrece taller gratuito para agricultores.',
                'cuerpo' => '<p>Temas: técnicas de riego, control de plagas orgánico.</p><p>Fecha: 20 de junio de 2026. Lugar: Centro Comunitario.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 90,
                'fecha_publicacion' => now()->subDays(55),
            ],
            [
                'titulo' => 'Suspensión de Agua Potable por Mantenimiento',
                'resumen' => 'Se suspenderá el servicio de agua potable en sectores del centro urbano.',
                'cuerpo' => '<p>Fecha: 25 de junio de 2026 de 8:00 a 16:00.</p><p>Se recomienda almacenar agua con anticipación.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 275,
                'fecha_publicacion' => now()->subDays(58),
            ],
            [
                'titulo' => 'Concurso de Fotografía Municipal',
                'resumen' => 'El GAMA convoca al concurso de fotografía "Achocalla en Imágenes".',
                'cuerpo' => '<p>Tema: belleza natural y cultural del municipio.</p><p>Premios: Bs. 500 al primer lugar. Fecha límite: 30 de junio de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 160,
                'fecha_publicacion' => now()->subDays(60),
            ],
            [
                'titulo' => 'Inauguración de Biblioteca Municipal',
                'resumen' => 'Se inaugura la nueva Biblioteca Municipal con más de 5.000 libros.',
                'cuerpo' => '<p>Horario: lunes a viernes de 8:00 a 18:00.</p><p>Servicios gratuitos de préstamo y sala de lectura.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 320,
                'fecha_publicacion' => now()->subDays(62),
            ],
            [
                'titulo' => 'Campaña de Limpieza de Espacios Públicos',
                'resumen' => 'El GAMA organiza campaña de limpieza general en plazas y parques.',
                'cuerpo' => '<p>Fecha: 5 de julio de 2026. Participación voluntaria.</p><p>Se proporcionarán herramientas y refrigerios.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 185,
                'fecha_publicacion' => now()->subDays(65),
            ],
            [
                'titulo' => 'Actualización de Reglamentos Municipales',
                'resumen' => 'Se publican actualizaciones a los reglamentos de tránsito y comercio.',
                'cuerpo' => '<p>Disponibles en la página web del GAMA y oficinas municipales.</p><p>Entrada en vigencia: 1 de agosto de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 140,
                'fecha_publicacion' => now()->subDays(68),
            ],
            [
                'titulo' => 'Feria del Empleo Municipal',
                'resumen' => 'Se realiza feria del empleo con participación de empresas locales.',
                'cuerpo' => '<p>Fecha: 10 de julio de 2026. Lugar: Coliseo Municipal.</p><p>Ofertas de trabajo en diversos sectores.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 410,
                'fecha_publicacion' => now()->subDays(70),
            ],
            [
                'titulo' => 'Mantenimiento de Carreteras Vecinales',
                'resumen' => 'Inicio de trabajos de mantenimiento en carreteras de tierra.',
                'cuerpo' => '<p>Rutas: Achocalla - Villa Nueva y Achocalla - Alto Achocalla.</p><p>Duración: 15 días. Desvíos temporales.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 95,
                'fecha_publicacion' => now()->subDays(72),
            ],
            [
                'titulo' => 'Programa de Alimentación Escolar',
                'resumen' => 'El GAMA implementa programa de alimentación escolar en unidades educativas.',
                'cuerpo' => '<p>Beneficiarios: estudiantes de primaria y secundaria.</p><p>Inicio: agosto de 2026. Desayuno y almuerzo nutritivo.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 380,
                'fecha_publicacion' => now()->subDays(75),
            ],
            [
                'titulo' => 'Convocatoria a Elecciones Municipales 2026',
                'resumen' => 'Se convoca a elecciones municipales para elegir autoridades locales.',
                'cuerpo' => '<p>Fecha: 30 de noviembre de 2026.</p><p>Inscripción de candidatos: hasta el 30 de septiembre de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 500,
                'fecha_publicacion' => now()->subDays(78),
            ],
            [
                'titulo' => 'Instalación de Semáforos en Intersecciones Principales',
                'resumen' => 'El GAMA instala semáforos en puntos críticos del centro urbano.',
                'cuerpo' => '<p>Ubicaciones: Av. Principal con Calle 1 y Calle 2.</p><p>Inicio de operaciones: 1 de agosto de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 220,
                'fecha_publicacion' => now()->subDays(80),
            ],
            [
                'titulo' => 'Campaña de Prevención de Incendios Forestales',
                'resumen' => 'Se lanza campaña de prevención de incendios en zonas rurales.',
                'cuerpo' => '<p>Talleres informativos y distribución de material educativo.</p><p>Fecha: septiembre de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 125,
                'fecha_publicacion' => now()->subDays(82),
            ],
            [
                'titulo' => 'Construcción de Sistema de Riego Comunitario',
                'resumen' => 'Inicio de construcción de sistema de riego para agricultura.',
                'cuerpo' => '<p>Beneficiará a 50 familias agricultoras.</p><p>Inversión: Bs. 200.000. Plazo: 90 días.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 85,
                'fecha_publicacion' => now()->subDays(85),
            ],
            [
                'titulo' => 'Taller de Emprendimiento para Mujeres',
                'resumen' => 'La Dirección de la Mujer ofrece taller gratuito de emprendimiento.',
                'cuerpo' => '<p>Temas: elaboración de planes de negocio, marketing digital.</p><p>Fecha: 15 de septiembre de 2026. Dirigido a mujeres emprendedoras.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 170,
                'fecha_publicacion' => now()->subDays(88),
            ],
            [
                'titulo' => 'Suspensión de Clases por Feriado Nacional',
                'resumen' => 'No habrá clases en unidades educativas por feriado nacional.',
                'cuerpo' => '<p>Fecha: 6 de agosto de 2026 (Día de la Independencia).</p><p>Clases se reanudan el lunes 9 de agosto.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 290,
                'fecha_publicacion' => now()->subDays(90),
            ],
            [
                'titulo' => 'Programa de Becas para Estudiantes Destacados',
                'resumen' => 'El GAMA otorgará becas a estudiantes con alto rendimiento académico.',
                'cuerpo' => '<p>Beneficio: Bs. 500 mensuales por semestre.</p><p>Requisitos: promedio mínimo 85. Postulación: octubre de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 340,
                'fecha_publicacion' => now()->subDays(92),
            ],
            [
                'titulo' => 'Mantenimiento de Alumbrado Público',
                'resumen' => 'Trabajos de reparación y reemplazo de luminarias en calles principales.',
                'cuerpo' => '<p>Zonas: centro urbano y avenidas principales.</p><p>Duración: 10 días. Posibles interrupciones nocturnas.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 105,
                'fecha_publicacion' => now()->subDays(95),
            ],
            [
                'titulo' => 'Festival de la Papa 2026',
                'resumen' => 'Celebración del Festival de la Papa con exposición de variedades locales.',
                'cuerpo' => '<p>Fecha: 20 de octubre de 2026. Lugar: Plaza Principal.</p><p>Actividades culturales y venta de productos derivados.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 450,
                'fecha_publicacion' => now()->subDays(98),
            ],
            [
                'titulo' => 'Campaña de Vacunación contra la Influenza',
                'resumen' => 'SEDES La Paz realiza campaña gratuita de vacunación contra influenza.',
                'cuerpo' => '<p>Fechas: noviembre de 2026. Grupos prioritarios: niños, adultos mayores, embarazadas.</p><p>Lugares: centros de salud municipales.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 200,
                'fecha_publicacion' => now()->subDays(100),
            ],
            [
                'titulo' => 'Construcción de Mercado Campesino',
                'resumen' => 'Inicio de construcción de mercado para comercialización de productos agrícolas.',
                'cuerpo' => '<p>Ubicación: zona sur del municipio.</p><p>Inversión: Bs. 800.000. Inauguración: enero de 2027.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 155,
                'fecha_publicacion' => now()->subDays(102),
            ],
            [
                'titulo' => 'Taller de Computación para Adultos Mayores',
                'resumen' => 'Curso gratuito de introducción a la computación para personas de la tercera edad.',
                'cuerpo' => '<p>Contenido: uso básico de computadora, internet, redes sociales.</p><p>Fecha: diciembre de 2026. Lugar: Biblioteca Municipal.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 130,
                'fecha_publicacion' => now()->subDays(105),
            ],
            [
                'titulo' => 'Programa de Reciclaje Municipal',
                'resumen' => 'El GAMA implementa programa de separación y reciclaje de residuos.',
                'cuerpo' => '<p>Puntos de recolección en plazas principales.</p><p>Inicio: enero de 2027. Capacitaciones incluidas.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 280,
                'fecha_publicacion' => now()->subDays(108),
            ],
            [
                'titulo' => 'Suspensión de Servicios por Fiestas Navideñas',
                'resumen' => 'Oficinas municipales cerrarán por fiestas de fin de año.',
                'cuerpo' => '<p>Fechas: 24 y 31 de diciembre de 2026, 1 de enero de 2027.</p><p>Servicios de urgencia disponibles.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 360,
                'fecha_publicacion' => now()->subDays(110),
            ],
            [
                'titulo' => 'Concurso de Pintura Infantil',
                'resumen' => 'La Dirección de Cultura convoca a concurso de pintura para niños.',
                'cuerpo' => '<p>Tema: "Mi Municipio Achocalla".</p><p>Premios: materiales artísticos. Fecha límite: 15 de diciembre de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 175,
                'fecha_publicacion' => now()->subDays(112),
            ],
            [
                'titulo' => 'Inauguración de Centro Deportivo Municipal',
                'resumen' => 'Se inaugura el nuevo Centro Deportivo con canchas de fútbol y básquet.',
                'cuerpo' => '<p>Horario: 6:00 a 22:00. Inscripciones abiertas.</p><p>Actividades: torneos, clases deportivas.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 420,
                'fecha_publicacion' => now()->subDays(115),
            ],
            [
                'titulo' => 'Campaña de Arborización Urbana',
                'resumen' => 'Plantación de árboles en parques y avenidas del municipio.',
                'cuerpo' => '<p>Fecha: marzo de 2027. Participación ciudadana.</p><p>Se plantarán 500 árboles nativos.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 145,
                'fecha_publicacion' => now()->subDays(118),
            ],
            [
                'titulo' => 'Actualización del Plan de Desarrollo Municipal',
                'resumen' => 'Se presenta la actualización del Plan de Desarrollo Municipal 2027-2031.',
                'cuerpo' => '<p>Disponible en la página web del GAMA.</p><p>Audiencias públicas: abril de 2027.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 260,
                'fecha_publicacion' => now()->subDays(120),
            ],
            [
                'titulo' => 'Programa de Turismo Comunitario',
                'resumen' => 'El GAMA promueve el turismo en comunidades rurales.',
                'cuerpo' => '<p>Rutas turísticas: cascadas, miradores, tradiciones culturales.</p><p>Información en la Dirección de Turismo.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 190,
                'fecha_publicacion' => now()->subDays(122),
            ],
            [
                'titulo' => 'Mantenimiento de Sistemas de Agua Potable',
                'resumen' => 'Trabajos de mantenimiento en la red de agua potable.',
                'cuerpo' => '<p>Zonas afectadas: comunidades rurales.</p><p>Duración: 5 días. Almacenar agua.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 115,
                'fecha_publicacion' => now()->subDays(125),
            ],
            [
                'titulo' => 'Feria Gastronómica Municipal',
                'resumen' => 'Exposición de platos típicos y productos culinarios locales.',
                'cuerpo' => '<p>Fecha: 10 de mayo de 2027. Lugar: Plaza Principal.</p><p>Participación de restaurantes y familias.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 380,
                'fecha_publicacion' => now()->subDays(128),
            ],
            [
                'titulo' => 'Campaña de Educación Vial',
                'resumen' => 'Talleres de educación vial para escolares y conductores.',
                'cuerpo' => '<p>Temas: normas de tránsito, seguridad peatonal.</p><p>Fecha: junio de 2027. En unidades educativas.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 220,
                'fecha_publicacion' => now()->subDays(130),
            ],
            [
                'titulo' => 'Construcción de Puente Vehicular',
                'resumen' => 'Inicio de construcción de puente sobre río para mejorar conectividad.',
                'cuerpo' => '<p>Inversión: Bs. 2.500.000. Plazo: 8 meses.</p><p>Beneficiará al comercio local.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 310,
                'fecha_publicacion' => now()->subDays(132),
            ],
            [
                'titulo' => 'Programa de Salud Mental Comunitaria',
                'resumen' => 'Servicios gratuitos de atención en salud mental.',
                'cuerpo' => '<p>Consultas psicológicas y psiquiátricas.</p><p>Lugar: Centro de Salud Municipal. Inicio: julio de 2027.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 165,
                'fecha_publicacion' => now()->subDays(135),
            ],
            [
                'titulo' => 'Actualización del Catastro Municipal',
                'resumen' => 'Actualización de información catastral para mejor gestión tributaria.',
                'cuerpo' => '<p>Levantamiento de datos en todas las comunidades.</p><p>Duración: 3 meses. Colaboración ciudadana requerida.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 95,
                'fecha_publicacion' => now()->subDays(138),
            ],
            [
                'titulo' => 'Festival de Música Andina',
                'resumen' => 'Celebración del Festival de Música Andina con artistas invitados.',
                'cuerpo' => '<p>Fecha: 15 de agosto de 2027. Lugar: Coliseo Municipal.</p><p>Entrada gratuita. Grupos folclóricos locales.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 470,
                'fecha_publicacion' => now()->subDays(140),
            ],
            [
                'titulo' => 'Campaña de Prevención de Violencia Intrafamiliar',
                'resumen' => 'Programa de sensibilización y apoyo a víctimas de violencia.',
                'cuerpo' => '<p>Talleres, charlas y línea de ayuda gratuita.</p><p>Disponible todo el año en la Dirección de la Mujer.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 240,
                'fecha_publicacion' => now()->subDays(142),
            ],
            [
                'titulo' => 'Instalación de Cámaras de Seguridad',
                'resumen' => 'El GAMA instala cámaras de videovigilancia en puntos estratégicos.',
                'cuerpo' => '<p>Zonas: centro urbano y plazas principales.</p><p>Inicio: septiembre de 2027. Monitoreo 24/7.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 180,
                'fecha_publicacion' => now()->subDays(145),
            ],
            [
                'titulo' => 'Programa de Capacitación en Oficios',
                'resumen' => 'Cursos gratuitos de carpintería, electricidad y plomería.',
                'cuerpo' => '<p>Dirigido a jóvenes desempleados.</p><p>Duración: 6 meses. Certificación incluida.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 350,
                'fecha_publicacion' => now()->subDays(148),
            ],
            [
                'titulo' => 'Mantenimiento de Infraestructura Educativa',
                'resumen' => 'Reparaciones en unidades educativas del municipio.',
                'cuerpo' => '<p>Trabajos: pintura, techos, baños.</p><p>Durante vacaciones de invierno 2027.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 125,
                'fecha_publicacion' => now()->subDays(150),
            ],
            [
                'titulo' => 'Concurso de Proyectos Productivos',
                'resumen' => 'Convocatoria para proyectos productivos innovadores.',
                'cuerpo' => '<p>Premios: hasta Bs. 10.000 para implementación.</p><p>Fecha límite: 30 de octubre de 2027.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 205,
                'fecha_publicacion' => now()->subDays(152),
            ],
            [
                'titulo' => 'Suspensión Temporal de Servicios en Centro de Salud',
                'resumen' => 'El Centro de Salud Municipal permanecerá cerrado por mantenimiento el próximo fin de semana.',
                'cuerpo' => '<p>Debido a trabajos de mantenimiento eléctrico, el Centro de Salud Municipal estará cerrado desde el sábado 10 de abril hasta el lunes 12 de abril de 2026.</p><p>Los servicios de urgencia estarán disponibles en el Hospital de La Paz.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 95,
                'fecha_publicacion' => now()->subDays(20),
            ],
            [
                'titulo' => 'Feria Municipal de Artesanías y Productos Locales',
                'resumen' => 'Se invita a la población a participar en la Feria Municipal que se realizará este fin de semana en la plaza principal.',
                'cuerpo' => '<p>La feria contará con stands de artesanías, productos agrícolas y gastronómicos locales.</p><p>Horario: sábado y domingo de 9:00 a 18:00. Entrada libre.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 210,
                'fecha_publicacion' => now()->subDays(22),
            ],
            [
                'titulo' => 'Convocatoria para Voluntarios en Campaña de Reforestación',
                'resumen' => 'El GAMA busca voluntarios para participar en la campaña de reforestación programada para el mes próximo.',
                'cuerpo' => '<p>Fecha: 25 de abril de 2026. Lugar: Cerro Achocalla.</p><p>Se proporcionarán herramientas y refrigerios. Inscripciones en la Dirección de Medio Ambiente.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 145,
                'fecha_publicacion' => now()->subDays(25),
            ],
            [
                'titulo' => 'Actualización del Horario de Recolección de Basura',
                'resumen' => 'A partir de la próxima semana, el horario de recolección de basura en el centro urbano cambia.',
                'cuerpo' => '<p>Nuevo horario: lunes, miércoles y viernes de 6:00 a 8:00. Se solicita depositar la basura en bolsas cerradas.</p><p>Multas por incumplimiento: Bs. 50.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 320,
                'fecha_publicacion' => now()->subDays(28),
            ],
            [
                'titulo' => 'Inauguración de Nuevo Parque Infantil',
                'resumen' => 'El GAMA inaugura el nuevo parque infantil en la comunidad de Villa Nueva.',
                'cuerpo' => '<p>El parque cuenta con juegos infantiles, áreas verdes y bancas.</p><p>Inauguración: 15 de abril de 2026 a las 10:00. Invitados especiales: alcalde y concejales.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 280,
                'fecha_publicacion' => now()->subDays(30),
            ],
            [
                'titulo' => 'Curso Gratuito de Primeros Auxilios',
                'resumen' => 'La Dirección de Salud Municipal ofrece curso gratuito de primeros auxilios para la comunidad.',
                'cuerpo' => '<p>Fechas: 20 y 22 de abril de 2026. Lugar: Centro de Salud Municipal.</p><p>Dirigido a: adultos mayores y jóvenes. Cupos limitados.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 165,
                'fecha_publicacion' => now()->subDays(32),
            ],
            [
                'titulo' => 'Suspensión de Clases por Día del Trabajador',
                'resumen' => 'Las unidades educativas del municipio suspenderán clases el 1 de mayo de 2026.',
                'cuerpo' => '<p>En conmemoración del Día del Trabajador, no habrá clases en todas las unidades educativas fiscales y privadas.</p><p>Las clases se reanudan el martes 2 de mayo.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 400,
                'fecha_publicacion' => now()->subDays(35),
            ],
            [
                'titulo' => 'Licitación para Suministro de Materiales de Construcción',
                'resumen' => 'Se convoca a proveedores a participar en la licitación para suministro de materiales de construcción.',
                'cuerpo' => '<p>Presupuesto: Bs. 1.200.000. Fecha límite: 10 de mayo de 2026.</p><p>Información en la Unidad de Contrataciones del GAMA.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 85,
                'fecha_publicacion' => now()->subDays(38),
            ],
            [
                'titulo' => 'Campaña de Donación de Sangre',
                'resumen' => 'El Banco de Sangre Municipal realiza campaña de donación voluntaria.',
                'cuerpo' => '<p>Fecha: 5 de mayo de 2026. Lugar: Centro de Salud.</p><p>Requisitos: mayor de 18 años, peso mínimo 50 kg. Traer documento de identidad.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 195,
                'fecha_publicacion' => now()->subDays(40),
            ],
            [
                'titulo' => 'Mantenimiento de Redes Eléctricas en Zona Norte',
                'resumen' => 'Se informa sobre trabajos de mantenimiento en las redes eléctricas de la zona norte del municipio.',
                'cuerpo' => '<p>Fechas: 8 al 12 de mayo de 2026. Posibles interrupciones de servicio.</p><p>Se solicita comprensión de la población.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 110,
                'fecha_publicacion' => now()->subDays(42),
            ],
            [
                'titulo' => 'Festival Cultural Municipal 2026',
                'resumen' => 'El GAMA organiza el Festival Cultural Municipal con participación de artistas locales.',
                'cuerpo' => '<p>Fecha: 15 de mayo de 2026. Lugar: Plaza Principal.</p><p>Actividades: música, danza, teatro y gastronomía típica.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 350,
                'fecha_publicacion' => now()->subDays(45),
            ],
            [
                'titulo' => 'Programa de Apoyo a Emprendedores',
                'resumen' => 'Se lanza programa de apoyo económico para emprendedores del municipio.',
                'cuerpo' => '<p>Subvenciones de hasta Bs. 5.000 para proyectos productivos.</p><p>Inscripciones: hasta el 30 de mayo de 2026 en la Dirección de Desarrollo Económico.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 225,
                'fecha_publicacion' => now()->subDays(48),
            ],
            [
                'titulo' => 'Censo Poblacional 2026',
                'resumen' => 'El Gobierno Nacional realiza censo poblacional en todo el país.',
                'cuerpo' => '<p>Fecha: 15 de junio de 2026. Participación obligatoria.</p><p>Información en las subalcaldías y centros educativos.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 480,
                'fecha_publicacion' => now()->subDays(50),
            ],
            [
                'titulo' => 'Construcción de Puente Peatonal en Río Achocalla',
                'resumen' => 'Inicio de construcción de puente peatonal para mejorar la conectividad.',
                'cuerpo' => '<p>Inversión: Bs. 300.000. Plazo: 60 días.</p><p>Beneficiará a comunidades ribereñas.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 135,
                'fecha_publicacion' => now()->subDays(52),
            ],
            [
                'titulo' => 'Taller de Capacitación en Agricultura Sostenible',
                'resumen' => 'La Dirección de Desarrollo Rural ofrece taller gratuito para agricultores.',
                'cuerpo' => '<p>Temas: técnicas de riego, control de plagas orgánico.</p><p>Fecha: 20 de junio de 2026. Lugar: Centro Comunitario.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 90,
                'fecha_publicacion' => now()->subDays(55),
            ],
            [
                'titulo' => 'Suspensión de Agua Potable por Mantenimiento',
                'resumen' => 'Se suspenderá el servicio de agua potable en sectores del centro urbano.',
                'cuerpo' => '<p>Fecha: 25 de junio de 2026 de 8:00 a 16:00.</p><p>Se recomienda almacenar agua con anticipación.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 275,
                'fecha_publicacion' => now()->subDays(58),
            ],
            [
                'titulo' => 'Concurso de Fotografía Municipal',
                'resumen' => 'El GAMA convoca al concurso de fotografía "Achocalla en Imágenes".',
                'cuerpo' => '<p>Tema: belleza natural y cultural del municipio.</p><p>Premios: Bs. 500 al primer lugar. Fecha límite: 30 de junio de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 160,
                'fecha_publicacion' => now()->subDays(60),
            ],
            [
                'titulo' => 'Inauguración de Biblioteca Municipal',
                'resumen' => 'Se inaugura la nueva Biblioteca Municipal con más de 5.000 libros.',
                'cuerpo' => '<p>Horario: lunes a viernes de 8:00 a 18:00.</p><p>Servicios gratuitos de préstamo y sala de lectura.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 320,
                'fecha_publicacion' => now()->subDays(62),
            ],
            [
                'titulo' => 'Campaña de Limpieza de Espacios Públicos',
                'resumen' => 'El GAMA organiza campaña de limpieza general en plazas y parques.',
                'cuerpo' => '<p>Fecha: 5 de julio de 2026. Participación voluntaria.</p><p>Se proporcionarán herramientas y refrigerios.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 185,
                'fecha_publicacion' => now()->subDays(65),
            ],
            [
                'titulo' => 'Actualización de Reglamentos Municipales',
                'resumen' => 'Se publican actualizaciones a los reglamentos de tránsito y comercio.',
                'cuerpo' => '<p>Disponibles en la página web del GAMA y oficinas municipales.</p><p>Entrada en vigencia: 1 de agosto de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 140,
                'fecha_publicacion' => now()->subDays(68),
            ],
            [
                'titulo' => 'Feria del Empleo Municipal',
                'resumen' => 'Se realiza feria del empleo con participación de empresas locales.',
                'cuerpo' => '<p>Fecha: 10 de julio de 2026. Lugar: Coliseo Municipal.</p><p>Ofertas de trabajo en diversos sectores.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 410,
                'fecha_publicacion' => now()->subDays(70),
            ],
            [
                'titulo' => 'Mantenimiento de Carreteras Vecinales',
                'resumen' => 'Inicio de trabajos de mantenimiento en carreteras de tierra.',
                'cuerpo' => '<p>Rutas: Achocalla - Villa Nueva y Achocalla - Alto Achocalla.</p><p>Duración: 15 días. Desvíos temporales.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 95,
                'fecha_publicacion' => now()->subDays(72),
            ],
            [
                'titulo' => 'Programa de Alimentación Escolar',
                'resumen' => 'El GAMA implementa programa de alimentación escolar en unidades educativas.',
                'cuerpo' => '<p>Beneficiarios: estudiantes de primaria y secundaria.</p><p>Inicio: agosto de 2026. Desayuno y almuerzo nutritivo.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 380,
                'fecha_publicacion' => now()->subDays(75),
            ],
            [
                'titulo' => 'Convocatoria a Elecciones Municipales 2026',
                'resumen' => 'Se convoca a elecciones municipales para elegir autoridades locales.',
                'cuerpo' => '<p>Fecha: 30 de noviembre de 2026.</p><p>Inscripción de candidatos: hasta el 30 de septiembre de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 500,
                'fecha_publicacion' => now()->subDays(78),
            ],
            [
                'titulo' => 'Instalación de Semáforos en Intersecciones Principales',
                'resumen' => 'El GAMA instala semáforos en puntos críticos del centro urbano.',
                'cuerpo' => '<p>Ubicaciones: Av. Principal con Calle 1 y Calle 2.</p><p>Inicio de operaciones: 1 de agosto de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 220,
                'fecha_publicacion' => now()->subDays(80),
            ],
            [
                'titulo' => 'Campaña de Prevención de Incendios Forestales',
                'resumen' => 'Se lanza campaña de prevención de incendios en zonas rurales.',
                'cuerpo' => '<p>Talleres informativos y distribución de material educativo.</p><p>Fecha: septiembre de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 125,
                'fecha_publicacion' => now()->subDays(82),
            ],
            [
                'titulo' => 'Construcción de Sistema de Riego Comunitario',
                'resumen' => 'Inicio de construcción de sistema de riego para agricultura.',
                'cuerpo' => '<p>Beneficiará a 50 familias agricultoras.</p><p>Inversión: Bs. 200.000. Plazo: 90 días.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 85,
                'fecha_publicacion' => now()->subDays(85),
            ],
            [
                'titulo' => 'Taller de Emprendimiento para Mujeres',
                'resumen' => 'La Dirección de la Mujer ofrece taller gratuito de emprendimiento.',
                'cuerpo' => '<p>Temas: elaboración de planes de negocio, marketing digital.</p><p>Fecha: 15 de septiembre de 2026. Dirigido a mujeres emprendedoras.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 170,
                'fecha_publicacion' => now()->subDays(88),
            ],
            [
                'titulo' => 'Suspensión de Clases por Feriado Nacional',
                'resumen' => 'No habrá clases en unidades educativas por feriado nacional.',
                'cuerpo' => '<p>Fecha: 6 de agosto de 2026 (Día de la Independencia).</p><p>Clases se reanudan el lunes 9 de agosto.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 290,
                'fecha_publicacion' => now()->subDays(90),
            ],
            [
                'titulo' => 'Programa de Becas para Estudiantes Destacados',
                'resumen' => 'El GAMA otorgará becas a estudiantes con alto rendimiento académico.',
                'cuerpo' => '<p>Beneficio: Bs. 500 mensuales por semestre.</p><p>Requisitos: promedio mínimo 85. Postulación: octubre de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 340,
                'fecha_publicacion' => now()->subDays(92),
            ],
            [
                'titulo' => 'Mantenimiento de Alumbrado Público',
                'resumen' => 'Trabajos de reparación y reemplazo de luminarias en calles principales.',
                'cuerpo' => '<p>Zonas: centro urbano y avenidas principales.</p><p>Duración: 10 días. Posibles interrupciones nocturnas.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 105,
                'fecha_publicacion' => now()->subDays(95),
            ],
            [
                'titulo' => 'Festival de la Papa 2026',
                'resumen' => 'Celebración del Festival de la Papa con exposición de variedades locales.',
                'cuerpo' => '<p>Fecha: 20 de octubre de 2026. Lugar: Plaza Principal.</p><p>Actividades culturales y venta de productos derivados.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 450,
                'fecha_publicacion' => now()->subDays(98),
            ],
            [
                'titulo' => 'Campaña de Vacunación contra la Influenza',
                'resumen' => 'SEDES La Paz realiza campaña gratuita de vacunación contra influenza.',
                'cuerpo' => '<p>Fechas: noviembre de 2026. Grupos prioritarios: niños, adultos mayores, embarazadas.</p><p>Lugares: centros de salud municipales.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 200,
                'fecha_publicacion' => now()->subDays(100),
            ],
            [
                'titulo' => 'Construcción de Mercado Campesino',
                'resumen' => 'Inicio de construcción de mercado para comercialización de productos agrícolas.',
                'cuerpo' => '<p>Ubicación: zona sur del municipio.</p><p>Inversión: Bs. 800.000. Inauguración: enero de 2027.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 155,
                'fecha_publicacion' => now()->subDays(102),
            ],
            [
                'titulo' => 'Taller de Computación para Adultos Mayores',
                'resumen' => 'Curso gratuito de introducción a la computación para personas de la tercera edad.',
                'cuerpo' => '<p>Contenido: uso básico de computadora, internet, redes sociales.</p><p>Fecha: diciembre de 2026. Lugar: Biblioteca Municipal.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 130,
                'fecha_publicacion' => now()->subDays(105),
            ],
            [
                'titulo' => 'Programa de Reciclaje Municipal',
                'resumen' => 'El GAMA implementa programa de separación y reciclaje de residuos.',
                'cuerpo' => '<p>Puntos de recolección en plazas principales.</p><p>Inicio: enero de 2027. Capacitaciones incluidas.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 280,
                'fecha_publicacion' => now()->subDays(108),
            ],
            [
                'titulo' => 'Suspensión de Servicios por Fiestas Navideñas',
                'resumen' => 'Oficinas municipales cerrarán por fiestas de fin de año.',
                'cuerpo' => '<p>Fechas: 24 y 31 de diciembre de 2026, 1 de enero de 2027.</p><p>Servicios de urgencia disponibles.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 360,
                'fecha_publicacion' => now()->subDays(110),
            ],
            [
                'titulo' => 'Concurso de Pintura Infantil',
                'resumen' => 'La Dirección de Cultura convoca a concurso de pintura para niños.',
                'cuerpo' => '<p>Tema: "Mi Municipio Achocalla".</p><p>Premios: materiales artísticos. Fecha límite: 15 de diciembre de 2026.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 175,
                'fecha_publicacion' => now()->subDays(112),
            ],
            [
                'titulo' => 'Inauguración de Centro Deportivo Municipal',
                'resumen' => 'Se inaugura el nuevo Centro Deportivo con canchas de fútbol y básquet.',
                'cuerpo' => '<p>Horario: 6:00 a 22:00. Inscripciones abiertas.</p><p>Actividades: torneos, clases deportivas.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 420,
                'fecha_publicacion' => now()->subDays(115),
            ],
            [
                'titulo' => 'Campaña de Arborización Urbana',
                'resumen' => 'Plantación de árboles en parques y avenidas del municipio.',
                'cuerpo' => '<p>Fecha: marzo de 2027. Participación ciudadana.</p><p>Se plantarán 500 árboles nativos.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 145,
                'fecha_publicacion' => now()->subDays(118),
            ],
            [
                'titulo' => 'Actualización del Plan de Desarrollo Municipal',
                'resumen' => 'Se presenta la actualización del Plan de Desarrollo Municipal 2027-2031.',
                'cuerpo' => '<p>Disponible en la página web del GAMA.</p><p>Audiencias públicas: abril de 2027.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 260,
                'fecha_publicacion' => now()->subDays(120),
            ],
            [
                'titulo' => 'Programa de Turismo Comunitario',
                'resumen' => 'El GAMA promueve el turismo en comunidades rurales.',
                'cuerpo' => '<p>Rutas turísticas: cascadas, miradores, tradiciones culturales.</p><p>Información en la Dirección de Turismo.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 190,
                'fecha_publicacion' => now()->subDays(122),
            ],
            [
                'titulo' => 'Mantenimiento de Sistemas de Agua Potable',
                'resumen' => 'Trabajos de mantenimiento en la red de agua potable.',
                'cuerpo' => '<p>Zonas afectadas: comunidades rurales.</p><p>Duración: 5 días. Almacenar agua.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 115,
                'fecha_publicacion' => now()->subDays(125),
            ],
            [
                'titulo' => 'Feria Gastronómica Municipal',
                'resumen' => 'Exposición de platos típicos y productos culinarios locales.',
                'cuerpo' => '<p>Fecha: 10 de mayo de 2027. Lugar: Plaza Principal.</p><p>Participación de restaurantes y familias.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 380,
                'fecha_publicacion' => now()->subDays(128),
            ],
            [
                'titulo' => 'Campaña de Educación Vial',
                'resumen' => 'Talleres de educación vial para escolares y conductores.',
                'cuerpo' => '<p>Temas: normas de tránsito, seguridad peatonal.</p><p>Fecha: junio de 2027. En unidades educativas.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 220,
                'fecha_publicacion' => now()->subDays(130),
            ],
            [
                'titulo' => 'Construcción de Puente Vehicular',
                'resumen' => 'Inicio de construcción de puente sobre río para mejorar conectividad.',
                'cuerpo' => '<p>Inversión: Bs. 2.500.000. Plazo: 8 meses.</p><p>Beneficiará al comercio local.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 310,
                'fecha_publicacion' => now()->subDays(132),
            ],
            [
                'titulo' => 'Programa de Salud Mental Comunitaria',
                'resumen' => 'Servicios gratuitos de atención en salud mental.',
                'cuerpo' => '<p>Consultas psicológicas y psiquiátricas.</p><p>Lugar: Centro de Salud Municipal. Inicio: julio de 2027.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 165,
                'fecha_publicacion' => now()->subDays(135),
            ],
            [
                'titulo' => 'Actualización del Catastro Municipal',
                'resumen' => 'Actualización de información catastral para mejor gestión tributaria.',
                'cuerpo' => '<p>Levantamiento de datos en todas las comunidades.</p><p>Duración: 3 meses. Colaboración ciudadana requerida.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 95,
                'fecha_publicacion' => now()->subDays(138),
            ],
            [
                'titulo' => 'Festival de Música Andina',
                'resumen' => 'Celebración del Festival de Música Andina con artistas invitados.',
                'cuerpo' => '<p>Fecha: 15 de agosto de 2027. Lugar: Coliseo Municipal.</p><p>Entrada gratuita. Grupos folclóricos locales.</p>',
                'imagen_url' => 'assets/img/all-images/service-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 470,
                'fecha_publicacion' => now()->subDays(140),
            ],
            [
                'titulo' => 'Campaña de Prevención de Violencia Intrafamiliar',
                'resumen' => 'Programa de sensibilización y apoyo a víctimas de violencia.',
                'cuerpo' => '<p>Talleres, charlas y línea de ayuda gratuita.</p><p>Disponible todo el año en la Dirección de la Mujer.</p>',
                'imagen_url' => 'assets/img/all-images/service-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 240,
                'fecha_publicacion' => now()->subDays(142),
            ],
            [
                'titulo' => 'Instalación de Cámaras de Seguridad',
                'resumen' => 'El GAMA instala cámaras de videovigilancia en puntos estratégicos.',
                'cuerpo' => '<p>Zonas: centro urbano y plazas principales.</p><p>Inicio: septiembre de 2027. Monitoreo 24/7.</p>',
                'imagen_url' => 'assets/img/all-images/service-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 180,
                'fecha_publicacion' => now()->subDays(145),
            ],
            [
                'titulo' => 'Programa de Capacitación en Oficios',
                'resumen' => 'Cursos gratuitos de carpintería, electricidad y plomería.',
                'cuerpo' => '<p>Dirigido a jóvenes desempleados.</p><p>Duración: 6 meses. Certificación incluida.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img1.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => true,
                'vistas' => 350,
                'fecha_publicacion' => now()->subDays(148),
            ],
            [
                'titulo' => 'Mantenimiento de Infraestructura Educativa',
                'resumen' => 'Reparaciones en unidades educativas del municipio.',
                'cuerpo' => '<p>Trabajos: pintura, techos, baños.</p><p>Durante vacaciones de invierno 2027.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img2.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 125,
                'fecha_publicacion' => now()->subDays(150),
            ],
            [
                'titulo' => 'Concurso de Proyectos Productivos',
                'resumen' => 'Convocatoria para proyectos productivos innovadores.',
                'cuerpo' => '<p>Premios: hasta Bs. 10.000 para implementación.</p><p>Fecha límite: 30 de octubre de 2027.</p>',
                'imagen_url' => 'assets/img/all-images/blog-img3.png',
                'archivo_url' => null,
                'estado' => 'publicado',
                'destacado' => false,
                'vistas' => 205,
                'fecha_publicacion' => now()->subDays(152),
            ],
        ];

        foreach ($comunicados as $index => $data) {
            DB::table('comunicados')->insert([
                ...$data,
                'slug' => Str::slug($data['titulo']).'-'.($index + 1),
                'created_at' => now(),
            ]);
        }
    }
}
