<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DirectorioInstitucionalSeeder extends Seeder
{
    public function run(): void
    {
        $registros = [

            [
                'secretaria_id'         => null,
                'nombre_unidad'         => 'Despacho del Alcalde Municipal',
                'descripcion'           => 'Máxima autoridad ejecutiva del Gobierno Autónomo Municipal. Responsable de la dirección política, administrativa y de gestión del municipio.',
                'titular'               => 'Lic. Freddy Mamani Condori',
                'cargo_responsable'     => 'Alcalde Municipal',
                'direccion_fisica'      => 'Palacio Municipal, Piso 3, Av. Bolívar s/n',
                'telefono_principal'    => '(02) 2204500',
                'telefono_secundario'   => '(02) 2204501',
                'email_institucional'   => 'alcalde@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => null,
                'orden'                 => 1,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => null,
                'nombre_unidad'         => 'Concejo Municipal',
                'descripcion'           => 'Órgano deliberativo, fiscalizador y legislativo del Gobierno Autónomo Municipal. Compuesto por concejales elegidos por voto popular.',
                'titular'               => 'Lic. Patricia Quispe Flores',
                'cargo_responsable'     => 'Presidenta del Concejo Municipal',
                'direccion_fisica'      => 'Palacio Municipal, Piso 2, Av. Bolívar s/n',
                'telefono_principal'    => '(02) 2204510',
                'telefono_secundario'   => null,
                'email_institucional'   => 'concejo@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => null,
                'orden'                 => 2,
                'activo'                => true,
            ],

            [
                'secretaria_id'         => 1,
                'nombre_unidad'         => 'Secretaría Municipal',
                'descripcion'           => 'Gestiona la documentación oficial, actas del Concejo, comunicaciones institucionales y coordinación entre unidades.',
                'titular'               => 'Lic. Carmen Rosa Flores Mamani',
                'cargo_responsable'     => 'Secretaria Municipal',
                'direccion_fisica'      => 'Palacio Municipal, Planta Baja, Ventanilla 1',
                'telefono_principal'    => '(02) 2204520',
                'telefono_secundario'   => '(02) 2204521',
                'email_institucional'   => 'secretaria.municipal@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 16:00',
                'horario_sabado'        => '08:30 - 12:30',
                'orden'                 => 3,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 1,
                'nombre_unidad'         => 'Gestión Documental y Archivo',
                'descripcion'           => 'Administra el archivo institucional, recepción de documentos y emisión de certificaciones municipales.',
                'titular'               => 'Téc. Miriam Condori Apaza',
                'cargo_responsable'     => 'Jefa de Archivo y Documentación',
                'direccion_fisica'      => 'Palacio Municipal, Planta Baja, Ventanilla 2',
                'telefono_principal'    => '(02) 2204522',
                'telefono_secundario'   => null,
                'email_institucional'   => 'archivo@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 16:00',
                'horario_sabado'        => '08:30 - 12:00',
                'orden'                 => 4,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 1,
                'nombre_unidad'         => 'Atención al Ciudadano',
                'descripcion'           => 'Ventanilla única de atención, orientación, recepción de quejas, sugerencias y seguimiento de trámites.',
                'titular'               => 'Lic. Ana Beatriz Vargas Chura',
                'cargo_responsable'     => 'Jefa de Atención al Ciudadano',
                'direccion_fisica'      => 'Palacio Municipal, Planta Baja, Ventanilla 3',
                'telefono_principal'    => '(02) 2204523',
                'telefono_secundario'   => '76001234',
                'email_institucional'   => 'atencion.ciudadana@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => '08:30 - 12:30',
                'orden'                 => 5,
                'activo'                => true,
            ],

            [
                'secretaria_id'         => 2,
                'nombre_unidad'         => 'Secretaría de Hacienda y Finanzas',
                'descripcion'           => 'Administra los recursos financieros municipales, presupuesto, contabilidad y tesorería.',
                'titular'               => 'Lic. Jorge Alberto Ticona Mamani',
                'cargo_responsable'     => 'Secretario de Hacienda y Finanzas',
                'direccion_fisica'      => 'Palacio Municipal, Piso 1',
                'telefono_principal'    => '(02) 2204530',
                'telefono_secundario'   => null,
                'email_institucional'   => 'hacienda@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 16:00',
                'horario_sabado'        => null,
                'orden'                 => 6,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 2,
                'nombre_unidad'         => 'Tesorería Municipal',
                'descripcion'           => 'Recaudación de impuestos municipales, pagos, cobros y administración de fondos públicos.',
                'titular'               => 'Lic. Rosa Elena Chura Poma',
                'cargo_responsable'     => 'Tesorera Municipal',
                'direccion_fisica'      => 'Palacio Municipal, Piso 1, Ventanilla Tesorería',
                'telefono_principal'    => '(02) 2204531',
                'telefono_secundario'   => null,
                'email_institucional'   => 'tesoreria@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:30 - 15:30',
                'horario_sabado'        => '08:30 - 12:00',
                'orden'                 => 7,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 2,
                'nombre_unidad'         => 'Contabilidad e Impuestos',
                'descripcion'           => 'Gestión contable institucional, liquidación de impuestos IEHD, patentes, RUAT y declaraciones tributarias.',
                'titular'               => 'Lic. Luis Fernando Mamani Callisaya',
                'cargo_responsable'     => 'Jefe de Contabilidad',
                'direccion_fisica'      => 'Palacio Municipal, Piso 1',
                'telefono_principal'    => '(02) 2204532',
                'telefono_secundario'   => null,
                'email_institucional'   => 'contabilidad@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 16:00',
                'horario_sabado'        => null,
                'orden'                 => 8,
                'activo'                => true,
            ],

            [
                'secretaria_id'         => 3,
                'nombre_unidad'         => 'Secretaría de Obras Públicas e Infraestructura',
                'descripcion'           => 'Planifica y ejecuta proyectos de infraestructura vial, construcciones municipales y mantenimiento urbano.',
                'titular'               => 'Ing. Carlos Ernesto Condori Flores',
                'cargo_responsable'     => 'Secretario de Obras Públicas',
                'direccion_fisica'      => 'Palacio Municipal, Piso 2',
                'telefono_principal'    => '(02) 2204540',
                'telefono_secundario'   => '79001234',
                'email_institucional'   => 'obras.publicas@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => null,
                'orden'                 => 9,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 3,
                'nombre_unidad'         => 'Proyectos e Ingeniería',
                'descripcion'           => 'Formulación, diseño y supervisión técnica de proyectos de infraestructura municipal.',
                'titular'               => 'Ing. Mario Huanca Quispe',
                'cargo_responsable'     => 'Jefe de Proyectos e Ingeniería',
                'direccion_fisica'      => 'Palacio Municipal, Piso 2',
                'telefono_principal'    => '(02) 2204541',
                'telefono_secundario'   => null,
                'email_institucional'   => 'proyectos@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 16:00',
                'horario_sabado'        => null,
                'orden'                 => 10,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 3,
                'nombre_unidad'         => 'Catastro Urbano y Rural',
                'descripcion'           => 'Registro, actualización y certificación catastral de bienes inmuebles urbanos y rurales del municipio.',
                'titular'               => 'Ing. Sandra Vargas Apaza',
                'cargo_responsable'     => 'Jefa de Catastro',
                'direccion_fisica'      => 'Palacio Municipal, Planta Baja, Ala Norte',
                'telefono_principal'    => '(02) 2204542',
                'telefono_secundario'   => null,
                'email_institucional'   => 'catastro@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:30 - 16:00',
                'horario_sabado'        => '08:30 - 12:00',
                'orden'                 => 11,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 3,
                'nombre_unidad'         => 'Residuos Sólidos y Aseo Urbano',
                'descripcion'           => 'Gestión integral de residuos sólidos, planificación de rutas de recolección y control de puntos críticos de basura.',
                'titular'               => 'Ing. Pedro Condori Ticona',
                'cargo_responsable'     => 'Jefe de Residuos Sólidos',
                'direccion_fisica'      => 'Calle Litoral 123, Módulo Municipal',
                'telefono_principal'    => '(02) 2204543',
                'telefono_secundario'   => '77123456',
                'email_institucional'   => 'residuos.solidos@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '07:00 - 16:00',
                'horario_sabado'        => '07:00 - 13:00',
                'orden'                 => 12,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 3,
                'nombre_unidad'         => 'Alumbrado Público',
                'descripcion'           => 'Instalación, mantenimiento y atención de reportes de luminarias defectuosas en vías públicas y espacios municipales.',
                'titular'               => 'Téc. Roberto Mamani Apaza',
                'cargo_responsable'     => 'Encargado de Alumbrado Público',
                'direccion_fisica'      => 'Calle Litoral 123, Módulo Municipal',
                'telefono_principal'    => '(02) 2204544',
                'telefono_secundario'   => '75432100',
                'email_institucional'   => 'alumbrado@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => '08:00 - 12:00',
                'orden'                 => 13,
                'activo'                => true,
            ],

            [
                'secretaria_id'         => 4,
                'nombre_unidad'         => 'Secretaría de Desarrollo Humano y Social',
                'descripcion'           => 'Promueve el desarrollo social, bienestar familiar, programas de salud, educación e inclusión social.',
                'titular'               => 'Lic. María del Carmen Llanos Torres',
                'cargo_responsable'     => 'Secretaria de Desarrollo Humano',
                'direccion_fisica'      => 'Calle Sucre 456, Centro Social Municipal',
                'telefono_principal'    => '(02) 2204550',
                'telefono_secundario'   => null,
                'email_institucional'   => 'desarrollo.humano@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => null,
                'orden'                 => 14,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 4,
                'nombre_unidad'         => 'Servicio Legal Integral Municipal (SLIM)',
                'descripcion'           => 'Atención gratuita en casos de violencia intrafamiliar, asesoría legal, psicológica y trabajo social para mujeres y familias vulnerables.',
                'titular'               => 'Dra. Verónica Quispe Mamani',
                'cargo_responsable'     => 'Directora del SLIM',
                'direccion_fisica'      => 'Calle Sucre 456, Centro Social Municipal, Piso 1',
                'telefono_principal'    => '(02) 2204551',
                'telefono_secundario'   => '800100200',
                'email_institucional'   => 'slim@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 18:00',
                'horario_sabado'        => '08:00 - 13:00',
                'orden'                 => 15,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 4,
                'nombre_unidad'         => 'Defensoría de la Niñez y Adolescencia (DNA)',
                'descripcion'           => 'Protección de derechos de niñas, niños y adolescentes. Atención de casos de vulneración, abandono y violencia contra menores.',
                'titular'               => 'Lic. Gabriela Torres Mendoza',
                'cargo_responsable'     => 'Defensora de la Niñez y Adolescencia',
                'direccion_fisica'      => 'Calle Sucre 456, Centro Social Municipal, Piso 1',
                'telefono_principal'    => '(02) 2204552',
                'telefono_secundario'   => '77654300',
                'email_institucional'   => 'dna@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => '08:30 - 12:00',
                'orden'                 => 16,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 4,
                'nombre_unidad'         => 'Adulto Mayor y Personas con Discapacidad',
                'descripcion'           => 'Programas de asistencia social, visitas domiciliarias, atención en centros diurnos y registro de personas con discapacidad del municipio.',
                'titular'               => 'Lic. Elena Morales Condori',
                'cargo_responsable'     => 'Jefa de Adulto Mayor y Discapacidad',
                'direccion_fisica'      => 'Calle Sucre 456, Centro Social Municipal, Piso 2',
                'telefono_principal'    => '(02) 2204553',
                'telefono_secundario'   => null,
                'email_institucional'   => 'adulto.mayor@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 16:00',
                'horario_sabado'        => null,
                'orden'                 => 17,
                'activo'                => true,
            ],

            [
                'secretaria_id'         => 5,
                'nombre_unidad'         => 'Secretaría de Medio Ambiente y Gestión de Riesgos',
                'descripcion'           => 'Gestión ambiental municipal, control de contaminación, áreas verdes, gestión de riesgos y atención de emergencias.',
                'titular'               => 'Lic. Sonia Patricia Mamani Flores',
                'cargo_responsable'     => 'Secretaria de Medio Ambiente',
                'direccion_fisica'      => 'Calle Arce 789, Edificio Ambiental',
                'telefono_principal'    => '(02) 2204560',
                'telefono_secundario'   => null,
                'email_institucional'   => 'medio.ambiente@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => null,
                'orden'                 => 18,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 5,
                'nombre_unidad'         => 'Control Ambiental y Calidad',
                'descripcion'           => 'Inspección de actividades contaminantes, control de ruido, emisiones y vertidos. Otorgación de licencias ambientales.',
                'titular'               => 'Ing. Carlos Ernesto Ticona Vargas',
                'cargo_responsable'     => 'Jefe de Control Ambiental',
                'direccion_fisica'      => 'Calle Arce 789, Edificio Ambiental, Piso 1',
                'telefono_principal'    => '(02) 2204561',
                'telefono_secundario'   => '78009900',
                'email_institucional'   => 'control.ambiental@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => '08:00 - 12:00',
                'orden'                 => 19,
                'activo'                => true,
            ],

            [
                'secretaria_id'         => 6,
                'nombre_unidad'         => 'Secretaría de Planificación y Desarrollo Económico',
                'descripcion'           => 'Elaboración del POA, PDM, gestión de cooperación, estadísticas municipales y fomento al desarrollo económico local.',
                'titular'               => 'Lic. Rolando Ernesto Apaza Condori',
                'cargo_responsable'     => 'Secretario de Planificación',
                'direccion_fisica'      => 'Palacio Municipal, Piso 2, Ala Oeste',
                'telefono_principal'    => '(02) 2204570',
                'telefono_secundario'   => null,
                'email_institucional'   => 'planificacion@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => null,
                'orden'                 => 20,
                'activo'                => true,
            ],

            [
                'secretaria_id'         => 7,
                'nombre_unidad'         => 'Secretaría Jurídica y Legal',
                'descripcion'           => 'Asesoría legal institucional, elaboración de contratos, ordenanzas, resoluciones y representación judicial del municipio.',
                'titular'               => 'Dr. Hernán Quispe Torrez',
                'cargo_responsable'     => 'Secretario Jurídico',
                'direccion_fisica'      => 'Palacio Municipal, Piso 3',
                'telefono_principal'    => '(02) 2204580',
                'telefono_secundario'   => null,
                'email_institucional'   => 'juridica@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => null,
                'orden'                 => 21,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 7,
                'nombre_unidad'         => 'Asesoría Legal y Contratos',
                'descripcion'           => 'Revisión y elaboración de contratos municipales, convenios interinstitucionales y documentos legales.',
                'titular'               => 'Ab. Silvia Rojas Mamani',
                'cargo_responsable'     => 'Asesora Legal',
                'direccion_fisica'      => 'Palacio Municipal, Piso 3',
                'telefono_principal'    => '(02) 2204581',
                'telefono_secundario'   => null,
                'email_institucional'   => 'asesoria.legal@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 16:00',
                'horario_sabado'        => null,
                'orden'                 => 22,
                'activo'                => true,
            ],

            [
                'secretaria_id'         => 8,
                'nombre_unidad'         => 'Secretaría de Cultura, Turismo y Deportes',
                'descripcion'           => 'Fomento de la cultura, identidad local, actividades turísticas, infraestructura deportiva y organización de eventos municipales.',
                'titular'               => 'Lic. Marcos Antonio Huanca Villca',
                'cargo_responsable'     => 'Secretario de Cultura, Turismo y Deportes',
                'direccion_fisica'      => 'Casa de la Cultura Municipal, Calle Murillo 100',
                'telefono_principal'    => '(02) 2204590',
                'telefono_secundario'   => '71234500',
                'email_institucional'   => 'cultura@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => '08:00 - 13:00',
                'orden'                 => 23,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => 8,
                'nombre_unidad'         => 'Coliseo y Complejos Deportivos',
                'descripcion'           => 'Administración, mantenimiento y reserva de instalaciones deportivas municipales: coliseo, canchas sintéticas y piscina.',
                'titular'               => 'Prof. Juan Carlos Flores Ticona',
                'cargo_responsable'     => 'Administrador de Instalaciones Deportivas',
                'direccion_fisica'      => 'Av. Estadio s/n, Complejo Deportivo Municipal',
                'telefono_principal'    => '(02) 2204591',
                'telefono_secundario'   => '76543210',
                'email_institucional'   => 'deportes@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '07:00 - 21:00',
                'horario_sabado'        => '07:00 - 20:00',
                'orden'                 => 24,
                'activo'                => true,
            ],

            [
                'secretaria_id'         => null,
                'nombre_unidad'         => 'Unidad de Comunicación e Imagen Institucional',
                'descripcion'           => 'Gestión de la comunicación pública, prensa, redes sociales, diseño institucional y relaciones con medios de comunicación.',
                'titular'               => 'Lic. Patricia Mamani Chura',
                'cargo_responsable'     => 'Jefa de Comunicación',
                'direccion_fisica'      => 'Palacio Municipal, Piso 1',
                'telefono_principal'    => '(02) 2204600',
                'telefono_secundario'   => '79800001',
                'email_institucional'   => 'comunicacion@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => '08:00 - 12:00',
                'orden'                 => 25,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => null,
                'nombre_unidad'         => 'Unidad de Transparencia y Lucha contra la Corrupción',
                'descripcion'           => 'Control interno, transparencia en la gestión pública, acceso a la información y recepción de denuncias de corrupción.',
                'titular'               => 'Lic. Roberto Choque Mamani',
                'cargo_responsable'     => 'Jefe de Transparencia',
                'direccion_fisica'      => 'Palacio Municipal, Piso 1',
                'telefono_principal'    => '(02) 2204601',
                'telefono_secundario'   => '800100300',
                'email_institucional'   => 'transparencia@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => null,
                'orden'                 => 26,
                'activo'                => true,
            ],
            [
                'secretaria_id'         => null,
                'nombre_unidad'         => 'Tecnologías de Información (TI)',
                'descripcion'           => 'Soporte técnico informático, administración de sistemas, redes, portales digitales y seguridad de la información institucional.',
                'titular'               => 'Ing. Álvaro Torrez Quispe',
                'cargo_responsable'     => 'Jefe de TI',
                'direccion_fisica'      => 'Palacio Municipal, Sótano',
                'telefono_principal'    => '(02) 2204602',
                'telefono_secundario'   => null,
                'email_institucional'   => 'ti@senefco.gob.bo',
                'foto_url'              => null,
                'horario_lunes_viernes' => '08:00 - 17:00',
                'horario_sabado'        => null,
                'orden'                 => 27,
                'activo'                => true,
            ],
        ];

        foreach ($registros as $reg) {
            DB::table('directorio_institucional')->insert($reg);
        }

        $this->command->info('✅ ' . count($registros) . ' registros del directorio institucional creados.');
    }
}
