<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EscalaSalarialPortalSeeder extends Seeder
{
    public function run(): void
    {
        $now = now()->toDateTimeString();

        $registros = [

            [
                'anio'            => 2026,
                'secretaria'      => 'Despacho del Alcalde',
                'cargo'           => 'Alcalde Municipal',
                'nivel'           => 'Directivo Superior',
                'categoria'       => 'Autoridad Electa',
                'salario_basico'  => 15_000.00,
                'bono_antiguedad' => 0.00,
                'bono_produccion' => 0.00,
                'otros_bonos'     => 2_500.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Concejo Municipal',
                'cargo'           => 'Concejal Municipal',
                'nivel'           => 'Directivo Superior',
                'categoria'       => 'Autoridad Electa',
                'salario_basico'  => 10_000.00,
                'bono_antiguedad' => 0.00,
                'bono_produccion' => 0.00,
                'otros_bonos'     => 1_500.00,
                'publicado'       => true,
            ],

            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Secretario Municipal / Director',
                'nivel'           => 'Directivo',
                'categoria'       => 'D1',
                'salario_basico'  => 9_500.00,
                'bono_antiguedad' => 500.00,
                'bono_produccion' => 800.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Jefe de Unidad / Departamento',
                'nivel'           => 'Directivo',
                'categoria'       => 'D2',
                'salario_basico'  => 7_200.00,
                'bono_antiguedad' => 400.00,
                'bono_produccion' => 600.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Responsable de Área',
                'nivel'           => 'Directivo',
                'categoria'       => 'D3',
                'salario_basico'  => 5_800.00,
                'bono_antiguedad' => 350.00,
                'bono_produccion' => 500.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],

            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Profesional I (Lic. / Ing. / Dr.)',
                'nivel'           => 'Profesional',
                'categoria'       => 'P1',
                'salario_basico'  => 5_200.00,
                'bono_antiguedad' => 300.00,
                'bono_produccion' => 400.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Profesional II',
                'nivel'           => 'Profesional',
                'categoria'       => 'P2',
                'salario_basico'  => 4_500.00,
                'bono_antiguedad' => 250.00,
                'bono_produccion' => 350.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Profesional III',
                'nivel'           => 'Profesional',
                'categoria'       => 'P3',
                'salario_basico'  => 3_800.00,
                'bono_antiguedad' => 200.00,
                'bono_produccion' => 300.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],

            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Técnico Superior I',
                'nivel'           => 'Técnico',
                'categoria'       => 'T1',
                'salario_basico'  => 3_500.00,
                'bono_antiguedad' => 180.00,
                'bono_produccion' => 250.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Técnico Superior II',
                'nivel'           => 'Técnico',
                'categoria'       => 'T2',
                'salario_basico'  => 3_100.00,
                'bono_antiguedad' => 160.00,
                'bono_produccion' => 200.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Técnico Medio',
                'nivel'           => 'Técnico',
                'categoria'       => 'T3',
                'salario_basico'  => 2_800.00,
                'bono_antiguedad' => 140.00,
                'bono_produccion' => 180.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],

            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Secretaria Ejecutiva / Asistente Administrativo',
                'nivel'           => 'Administrativo',
                'categoria'       => 'A1',
                'salario_basico'  => 3_200.00,
                'bono_antiguedad' => 160.00,
                'bono_produccion' => 200.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Auxiliar Administrativo I',
                'nivel'           => 'Administrativo',
                'categoria'       => 'A2',
                'salario_basico'  => 2_900.00,
                'bono_antiguedad' => 140.00,
                'bono_produccion' => 150.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Auxiliar Administrativo II',
                'nivel'           => 'Administrativo',
                'categoria'       => 'A3',
                'salario_basico'  => 2_650.00,
                'bono_antiguedad' => 120.00,
                'bono_produccion' => 130.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],

            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Operador de Maquinaria Pesada',
                'nivel'           => 'Operativo',
                'categoria'       => 'O1',
                'salario_basico'  => 3_400.00,
                'bono_antiguedad' => 170.00,
                'bono_produccion' => 220.00,
                'otros_bonos'     => 300.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Obras Públicas / Residuos Sólidos',
                'cargo'           => 'Chofer de Vehículo Municipal',
                'nivel'           => 'Operativo',
                'categoria'       => 'O2',
                'salario_basico'  => 3_000.00,
                'bono_antiguedad' => 150.00,
                'bono_produccion' => 180.00,
                'otros_bonos'     => 200.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Obras Públicas / Residuos Sólidos',
                'cargo'           => 'Trabajador de Limpieza y Aseo Urbano',
                'nivel'           => 'Operativo',
                'categoria'       => 'O3',
                'salario_basico'  => 2_700.00,
                'bono_antiguedad' => 130.00,
                'bono_produccion' => 0.00,
                'otros_bonos'     => 200.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Portero / Vigilante',
                'nivel'           => 'Operativo',
                'categoria'       => 'O4',
                'salario_basico'  => 2_500.00,
                'bono_antiguedad' => 100.00,
                'bono_produccion' => 0.00,
                'otros_bonos'     => 150.00,
                'publicado'       => true,
            ],

            [
                'anio'            => 2026,
                'secretaria'      => 'Secretaría Jurídica y Legal',
                'cargo'           => 'Asesor Legal / Abogado Municipal',
                'nivel'           => 'Profesional',
                'categoria'       => 'P1-E',
                'salario_basico'  => 5_500.00,
                'bono_antiguedad' => 300.00,
                'bono_produccion' => 450.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Secretaría de Obras Públicas',
                'cargo'           => 'Ingeniero Civil / Supervisor de Obras',
                'nivel'           => 'Profesional',
                'categoria'       => 'P1-E',
                'salario_basico'  => 5_800.00,
                'bono_antiguedad' => 300.00,
                'bono_produccion' => 500.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Secretaría de Desarrollo Humano',
                'cargo'           => 'Médico / Profesional en Salud',
                'nivel'           => 'Profesional',
                'categoria'       => 'P1-E',
                'salario_basico'  => 6_200.00,
                'bono_antiguedad' => 350.00,
                'bono_produccion' => 500.00,
                'otros_bonos'     => 800.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Secretaría de Desarrollo Humano',
                'cargo'           => 'Trabajador/a Social',
                'nivel'           => 'Profesional',
                'categoria'       => 'P2-E',
                'salario_basico'  => 4_200.00,
                'bono_antiguedad' => 220.00,
                'bono_produccion' => 300.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Secretaría de Desarrollo Humano',
                'cargo'           => 'Psicólogo/a Municipal',
                'nivel'           => 'Profesional',
                'categoria'       => 'P2-E',
                'salario_basico'  => 4_500.00,
                'bono_antiguedad' => 230.00,
                'bono_produccion' => 320.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Tecnologías de Información',
                'cargo'           => 'Ingeniero/a en Sistemas / Informático',
                'nivel'           => 'Profesional',
                'categoria'       => 'P1-E',
                'salario_basico'  => 5_500.00,
                'bono_antiguedad' => 280.00,
                'bono_produccion' => 450.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2026,
                'secretaria'      => 'Secretaría de Hacienda y Finanzas',
                'cargo'           => 'Contador Público / Auditor Interno',
                'nivel'           => 'Profesional',
                'categoria'       => 'P1-E',
                'salario_basico'  => 5_300.00,
                'bono_antiguedad' => 280.00,
                'bono_produccion' => 420.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],

            [
                'anio'            => 2025,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Secretario Municipal / Director',
                'nivel'           => 'Directivo',
                'categoria'       => 'D1',
                'salario_basico'  => 9_000.00,
                'bono_antiguedad' => 450.00,
                'bono_produccion' => 750.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2025,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Profesional I (Lic. / Ing. / Dr.)',
                'nivel'           => 'Profesional',
                'categoria'       => 'P1',
                'salario_basico'  => 4_900.00,
                'bono_antiguedad' => 280.00,
                'bono_produccion' => 370.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2025,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Técnico Superior I',
                'nivel'           => 'Técnico',
                'categoria'       => 'T1',
                'salario_basico'  => 3_300.00,
                'bono_antiguedad' => 165.00,
                'bono_produccion' => 230.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2025,
                'secretaria'      => 'Todas las Secretarías',
                'cargo'           => 'Auxiliar Administrativo I',
                'nivel'           => 'Administrativo',
                'categoria'       => 'A2',
                'salario_basico'  => 2_700.00,
                'bono_antiguedad' => 130.00,
                'bono_produccion' => 140.00,
                'otros_bonos'     => 0.00,
                'publicado'       => true,
            ],
            [
                'anio'            => 2025,
                'secretaria'      => 'Obras Públicas / Residuos Sólidos',
                'cargo'           => 'Trabajador de Limpieza y Aseo Urbano',
                'nivel'           => 'Operativo',
                'categoria'       => 'O3',
                'salario_basico'  => 2_500.00,
                'bono_antiguedad' => 120.00,
                'bono_produccion' => 0.00,
                'otros_bonos'     => 180.00,
                'publicado'       => true,
            ],
        ];

        foreach ($registros as &$reg) {
            $reg['created_at'] = $now;
            $reg['updated_at'] = $now;
        }

        DB::table('escala_salarial_portal')->insert($registros);

        $this->command->info('✅ ' . count($registros) . ' registros de escala salarial creados.');
    }
}
