<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EstadoProyectoPortalSeeder extends Seeder
{
    public function run(): void
    {
        $now = now()->toDateTimeString();

        $registros = [

            // ── EN EJECUCIÓN ──────────────────────────────────────────────────
            [
                'nombre'             => 'Pavimentación Av. Los Pinos — Tramo 1 (2.4 km)',
                'descripcion'        => 'Pavimentación con carpeta asfáltica de la Avenida Los Pinos desde la intersección con Calle Bolívar hasta el límite con el Barrio San Francisco. Incluye construcción de cunetas, badenes y señalización horizontal y vertical. Beneficia a 3.200 vecinos de los barrios Los Pinos, Villa Esperanza y San Francisco.',
                'secretaria'         => 'Secretaría de Obras Públicas e Infraestructura',
                'categoria'          => 'Infraestructura Vial',
                'ubicacion'          => 'Av. Los Pinos, Barrio Los Pinos — Villa Esperanza',
                'presupuesto'        => 2_850_000.00,
                'estado'             => 'en_ejecucion',
                'porcentaje_avance'  => 62.0,
                'fecha_inicio'       => '2026-01-15',
                'fecha_fin_estimada' => '2026-07-30',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Construcción Centro de Salud Integral — Barrio Norte',
                'descripcion'        => 'Construcción de infraestructura de salud de primer nivel en el Barrio Norte con ambientes para consulta externa, odontología, farmacia, laboratorio básico, sala de espera y servicios higiénicos. Capacidad de atención: 150 pacientes/día. Financiado con IDH.',
                'secretaria'         => 'Secretaría de Desarrollo Humano y Social',
                'categoria'          => 'Infraestructura Social',
                'ubicacion'          => 'Calle 5 de Agosto esq. Av. Cívica, Barrio Norte',
                'presupuesto'        => 1_450_000.00,
                'estado'             => 'en_ejecucion',
                'porcentaje_avance'  => 38.0,
                'fecha_inicio'       => '2026-02-01',
                'fecha_fin_estimada' => '2026-11-30',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Sistema de Alumbrado LED — Zona Sur (420 luminarias)',
                'descripcion'        => 'Instalación de 420 luminarias LED de alta eficiencia energética en la Zona Sur del municipio. El proyecto incluye sustitución de luminarias de sodio obsoletas, instalación de nuevos postes de concreto en calles sin alumbrado, cableado subterráneo en el área central y sistema de telegestión inteligente.',
                'secretaria'         => 'Secretaría de Obras Públicas e Infraestructura',
                'categoria'          => 'Servicios Básicos',
                'ubicacion'          => 'Zona Sur — Barrios Villa Fátima, 12 de Octubre, El Progreso',
                'presupuesto'        => 980_000.00,
                'estado'             => 'en_ejecucion',
                'porcentaje_avance'  => 75.0,
                'fecha_inicio'       => '2025-11-01',
                'fecha_fin_estimada' => '2026-05-31',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Mejoramiento Mercado Municipal Central — 2da Etapa',
                'descripcion'        => 'Segunda etapa del mejoramiento del Mercado Municipal Central: construcción de puestos de venta de material noble, instalación de sistema de agua y desagüe, mejoramiento de pisos, cubiertas metálicas y señalética de orden por rubros. Beneficia a 280 comerciantes y miles de usuarios diarios.',
                'secretaria'         => 'Secretaría de Planificación y Desarrollo Económico',
                'categoria'          => 'Infraestructura Económica',
                'ubicacion'          => 'Mercado Central, Calle Comercio s/n',
                'presupuesto'        => 1_200_000.00,
                'estado'             => 'en_ejecucion',
                'porcentaje_avance'  => 50.0,
                'fecha_inicio'       => '2026-01-20',
                'fecha_fin_estimada' => '2026-08-31',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Construcción Canchas Deportivas Multifuncionales — 6 barrios',
                'descripcion'        => 'Construcción de 6 canchas deportivas multifuncionales con piso de cemento pulido, pintura demarcatoria, arcos de fútbol y tableros de básquet, iluminación nocturna y gradería cubierta. Una cancha por barrio: Villa Esperanza, San Martín, Los Pinos, 16 de Julio, El Mirador y Nueva Vida.',
                'secretaria'         => 'Secretaría de Cultura, Turismo y Deportes',
                'categoria'          => 'Infraestructura Deportiva',
                'ubicacion'          => 'Barrios: Villa Esperanza, San Martín, Los Pinos, 16 de Julio, El Mirador, Nueva Vida',
                'presupuesto'        => 720_000.00,
                'estado'             => 'en_ejecucion',
                'porcentaje_avance'  => 83.0,
                'fecha_inicio'       => '2025-10-01',
                'fecha_fin_estimada' => '2026-04-30',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Planta de Tratamiento de Residuos Sólidos — Módulo 1',
                'descripcion'        => 'Construcción del primer módulo de la Planta Municipal de Tratamiento de Residuos Sólidos. Incluye área de clasificación manual, compactadoras, contenedores diferenciados por tipo de residuo, zona de compostaje para residuos orgánicos y cerco perimetral. Capacidad inicial: 12 toneladas/día.',
                'secretaria'         => 'Secretaría de Medio Ambiente y Gestión de Riesgos',
                'categoria'          => 'Gestión Ambiental',
                'ubicacion'          => 'Km 8 Carretera Norte, Zona Industrial Municipal',
                'presupuesto'        => 2_100_000.00,
                'estado'             => 'en_ejecucion',
                'porcentaje_avance'  => 29.0,
                'fecha_inicio'       => '2026-03-01',
                'fecha_fin_estimada' => '2027-03-31',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],

            // ── PLANIFICACIÓN ─────────────────────────────────────────────────
            [
                'nombre'             => 'Pavimentación Anillo Vial Sur — Tramo 2 (3.1 km)',
                'descripcion'        => 'Pavimentación del Anillo Vial Sur desde la intersección con la Av. Los Pinos hasta el empalme con la Carretera Departamental. Incluye estudio de suelos, diseño final, señalización vial y obras complementarias de drenaje. Proyecto financiado con IDH y recursos propios.',
                'secretaria'         => 'Secretaría de Obras Públicas e Infraestructura',
                'categoria'          => 'Infraestructura Vial',
                'ubicacion'          => 'Anillo Vial Sur — Zona Periurbana',
                'presupuesto'        => 4_200_000.00,
                'estado'             => 'planificacion',
                'porcentaje_avance'  => 0.0,
                'fecha_inicio'       => '2026-06-01',
                'fecha_fin_estimada' => '2027-06-30',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Centro de Desarrollo Integral para la Mujer (CDIM)',
                'descripcion'        => 'Construcción del Centro de Desarrollo Integral para la Mujer con ambientes para capacitación laboral, sala de reuniones, guardería municipal, consultorio psicológico y legal (SLIM), y espacios de emprendimiento. Atenderá a más de 500 mujeres del municipio.',
                'secretaria'         => 'Secretaría de Desarrollo Humano y Social',
                'categoria'          => 'Infraestructura Social',
                'ubicacion'          => 'Terreno Municipal Calle Sucre 789, Zona Centro',
                'presupuesto'        => 1_800_000.00,
                'estado'             => 'planificacion',
                'porcentaje_avance'  => 0.0,
                'fecha_inicio'       => '2026-07-01',
                'fecha_fin_estimada' => '2027-09-30',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Sistema Integrado de Gestión Municipal (SIGM)',
                'descripcion'        => 'Implementación de plataforma informática integral para la gestión municipal: módulos de recursos humanos, finanzas, planilla, catastro, trámites ciudadanos y portal de transparencia. Incluye capacitación al personal y migración de datos históricos.',
                'secretaria'         => 'Tecnologías de Información',
                'categoria'          => 'Modernización Institucional',
                'ubicacion'          => 'Palacio Municipal — Todas las dependencias',
                'presupuesto'        => 650_000.00,
                'estado'             => 'planificacion',
                'porcentaje_avance'  => 0.0,
                'fecha_inicio'       => '2026-05-01',
                'fecha_fin_estimada' => '2026-12-31',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],

            // ── CONCLUIDO ─────────────────────────────────────────────────────
            [
                'nombre'             => 'Pavimentación Calle 6 de Agosto — Barrio Central (1.8 km)',
                'descripcion'        => 'Pavimentación con carpeta asfáltica de la Calle 6 de Agosto desde la Plaza Principal hasta la intersección con Av. Villarroel. Incluía construcción de aceras, sardineles, badenes y señalización vial. Proyecto ejecutado con Coparticipación Tributaria.',
                'secretaria'         => 'Secretaría de Obras Públicas e Infraestructura',
                'categoria'          => 'Infraestructura Vial',
                'ubicacion'          => 'Calle 6 de Agosto, Barrio Central',
                'presupuesto'        => 1_650_000.00,
                'estado'             => 'concluido',
                'porcentaje_avance'  => 100.0,
                'fecha_inicio'       => '2025-03-01',
                'fecha_fin_estimada' => '2025-09-30',
                'fecha_fin_real'     => '2025-10-15',
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Construcción Coliseo Deportivo Municipal — Capacidad 800 personas',
                'descripcion'        => 'Construcción del Coliseo Deportivo Municipal con cancha de básquetbol / voleibol reglamentaria, graderías con 800 asientos, camerinos, servicios higiénicos, accesos para personas con discapacidad e iluminación profesional. Inaugurado en agosto 2025.',
                'secretaria'         => 'Secretaría de Cultura, Turismo y Deportes',
                'categoria'          => 'Infraestructura Deportiva',
                'ubicacion'          => 'Av. Estadio s/n, Complejo Deportivo Municipal',
                'presupuesto'        => 3_500_000.00,
                'estado'             => 'concluido',
                'porcentaje_avance'  => 100.0,
                'fecha_inicio'       => '2024-06-01',
                'fecha_fin_estimada' => '2025-06-30',
                'fecha_fin_real'     => '2025-08-10',
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Mejoramiento Red de Agua Potable — Barrios Periurbanos (4 barrios)',
                'descripcion'        => 'Extensión y mejoramiento de la red de distribución de agua potable en los barrios Villa Nueva, El Porvenir, 20 de Octubre y Santa Bárbara. Incluye instalación de 8.4 km de tuberías, 4 cámaras rompe presión, 2 tanques de almacenamiento de 50.000 litros y conexiones domiciliarias.',
                'secretaria'         => 'Secretaría de Obras Públicas e Infraestructura',
                'categoria'          => 'Servicios Básicos',
                'ubicacion'          => 'Barrios Villa Nueva, El Porvenir, 20 de Octubre, Santa Bárbara',
                'presupuesto'        => 2_200_000.00,
                'estado'             => 'concluido',
                'porcentaje_avance'  => 100.0,
                'fecha_inicio'       => '2025-01-15',
                'fecha_fin_estimada' => '2025-08-31',
                'fecha_fin_real'     => '2025-09-05',
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Reforestación y Recuperación Áreas Verdes — Parque Ecológico Municipal',
                'descripcion'        => 'Reforestación con 1.200 especies nativas y ornamentales, construcción de senderos peatonales, instalación de bancas, juegos infantiles, pérgolas y sistema de riego automatizado en el Parque Ecológico Municipal. Proyecto ejecutado con participación de la comunidad.',
                'secretaria'         => 'Secretaría de Medio Ambiente y Gestión de Riesgos',
                'categoria'          => 'Gestión Ambiental',
                'ubicacion'          => 'Parque Ecológico Municipal, Zona Norte',
                'presupuesto'        => 480_000.00,
                'estado'             => 'concluido',
                'porcentaje_avance'  => 100.0,
                'fecha_inicio'       => '2025-04-01',
                'fecha_fin_estimada' => '2025-07-31',
                'fecha_fin_real'     => '2025-07-28',
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],

            // ── PARALIZADO ────────────────────────────────────────────────────
            [
                'nombre'             => 'Construcción Terminal de Buses Interdepartamental',
                'descripcion'        => 'Construcción de nueva Terminal de Buses con 24 andenes, sala de espera con capacidad para 500 personas, área comercial, servicios higiénicos, estacionamiento y accesos vehiculares. Proyecto paralizado por conflicto en adjudicación de terreno. Se espera resolución judicial.',
                'secretaria'         => 'Secretaría de Obras Públicas e Infraestructura',
                'categoria'          => 'Infraestructura de Transporte',
                'ubicacion'          => 'Salida Norte, Av. Circunvalación Km 3',
                'presupuesto'        => 8_500_000.00,
                'estado'             => 'paralizado',
                'porcentaje_avance'  => 12.0,
                'fecha_inicio'       => '2025-08-01',
                'fecha_fin_estimada' => '2027-12-31',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'nombre'             => 'Refacción y Ampliación Matadero Municipal',
                'descripcion'        => 'Refacción integral y ampliación del Matadero Municipal: construcción de nuevas salas de faena con pisos y paredes de cerámica sanitaria, sistema de refrigeración, tratamiento de efluentes y cámara de frío. Paralizado por observaciones del SENASAG al diseño técnico.',
                'secretaria'         => 'Secretaría de Planificación y Desarrollo Económico',
                'categoria'          => 'Infraestructura Económica',
                'ubicacion'          => 'Matadero Municipal, Zona Industrial Km 5',
                'presupuesto'        => 1_350_000.00,
                'estado'             => 'paralizado',
                'porcentaje_avance'  => 5.0,
                'fecha_inicio'       => '2025-09-01',
                'fecha_fin_estimada' => '2026-06-30',
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => true,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],

            // ── CANCELADO ─────────────────────────────────────────────────────
            [
                'nombre'             => 'Teleférico Turístico Cerro Mirador — Estudio de Factibilidad',
                'descripcion'        => 'Estudio de factibilidad técnica, ambiental y económica para la construcción de un teleférico turístico desde el centro urbano hasta la cima del Cerro Mirador. Proyecto cancelado por determinación del Concejo Municipal debido a restricciones presupuestarias y priorización de proyectos sociales.',
                'secretaria'         => 'Secretaría de Cultura, Turismo y Deportes',
                'categoria'          => 'Turismo',
                'ubicacion'          => 'Cerro Mirador — Zona Turística',
                'presupuesto'        => 180_000.00,
                'estado'             => 'cancelado',
                'porcentaje_avance'  => 0.0,
                'fecha_inicio'       => null,
                'fecha_fin_estimada' => null,
                'fecha_fin_real'     => null,
                'imagen_url'         => null,
                'publicado'          => false,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
        ];

        DB::table('estados_proyecto_portal')->insert($registros);

        $this->command->info('✅ ' . count($registros) . ' proyectos creados en estados_proyecto_portal.');
    }
}
