<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class EventosSeeder extends Seeder
{
    public function run(): void
    {
        $eventos = [
            [
                'tipo_evento_id' => 2,
                'creado_por' => 1,
                'titulo' => 'Acto Cívico por el Aniversario del Municipio',
                'descripcion' => 'Celebración del aniversario de fundación del municipio con actos protocolares, desfile cívico y presentaciones culturales.',
                'lugar' => 'Plaza Principal del Municipio',
                'latitud' => -16.4955,
                'longitud' => -68.1336,
                'fecha_inicio' => '2026-04-15 09:00:00',
                'fecha_fin' => '2026-04-15 13:00:00',
                'todo_el_dia' => false,
                'estado' => 'programado',
                'url_transmision' => null,
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 3,
                'creado_por' => 1,
                'titulo' => 'Reunión Ordinaria del Concejo Municipal - Abril 2026',
                'descripcion' => 'Sesión ordinaria del Concejo Municipal para tratar la agenda legislativa del mes, aprobación de ordenanzas y resoluciones pendientes.',
                'lugar' => 'Sala de Sesiones del Concejo Municipal',
                'latitud' => -16.4960,
                'longitud' => -68.1340,
                'fecha_inicio' => '2026-04-20 10:00:00',
                'fecha_fin' => '2026-04-20 13:00:00',
                'todo_el_dia' => false,
                'estado' => 'programado',
                'url_transmision' => 'https://senefco.gob.bo/transmision/concejo',
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 4,
                'creado_por' => 1,
                'titulo' => 'Festival de Música y Danza Folclórica Municipal',
                'descripcion' => 'Festival anual de música y danza que reúne a grupos folclóricos de todas las zonas del municipio para preservar y difundir el patrimonio cultural.',
                'lugar' => 'Auditorio del Centro Cultural Municipal',
                'latitud' => -16.4980,
                'longitud' => -68.1350,
                'fecha_inicio' => '2026-05-10 18:00:00',
                'fecha_fin' => '2026-05-10 22:00:00',
                'todo_el_dia' => false,
                'estado' => 'programado',
                'url_transmision' => null,
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 4,
                'creado_por' => 1,
                'titulo' => 'Exposición de Arte Local "Raíces"',
                'descripcion' => 'Exposición de artistas locales con obras que reflejan la identidad cultural del municipio. Entrada libre para toda la ciudadanía.',
                'lugar' => 'Galería Municipal de Arte',
                'latitud' => null,
                'longitud' => null,
                'fecha_inicio' => '2026-05-01 00:00:00',
                'fecha_fin' => '2026-05-15 00:00:00',
                'todo_el_dia' => true,
                'estado' => 'programado',
                'url_transmision' => null,
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 5,
                'creado_por' => 1,
                'titulo' => 'Campeonato Municipal de Fútbol Interbarrios 2026',
                'descripcion' => 'Torneo de fútbol que reúne a equipos representantes de los diferentes barrios del municipio, promoviendo la actividad física y la integración social.',
                'lugar' => 'Estadio Municipal',
                'latitud' => -16.5100,
                'longitud' => -68.1400,
                'fecha_inicio' => '2026-04-05 08:00:00',
                'fecha_fin' => '2026-06-30 18:00:00',
                'todo_el_dia' => false,
                'estado' => 'programado',
                'url_transmision' => null,
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 5,
                'creado_por' => 1,
                'titulo' => 'Maratón Municipal "Corre por tu Ciudad"',
                'descripcion' => 'Carrera atlética abierta a toda la ciudadanía con categorías para adultos, jóvenes y niños. Recorrido por las principales avenidas del municipio.',
                'lugar' => 'Av. Principal del Municipio',
                'latitud' => -16.4955,
                'longitud' => -68.1336,
                'fecha_inicio' => '2026-05-24 07:00:00',
                'fecha_fin' => '2026-05-24 11:00:00',
                'todo_el_dia' => false,
                'estado' => 'programado',
                'url_transmision' => null,
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 6,
                'creado_por' => 1,
                'titulo' => 'Capacitación en Emprendimiento y Gestión de Negocios',
                'descripcion' => 'Taller gratuito para emprendedores y pequeños empresarios del municipio sobre gestión financiera, marketing digital y formalización de negocios.',
                'lugar' => 'Auditorio de la Secretaría de Planificación',
                'latitud' => null,
                'longitud' => null,
                'fecha_inicio' => '2026-04-22 14:00:00',
                'fecha_fin' => '2026-04-22 18:00:00',
                'todo_el_dia' => false,
                'estado' => 'programado',
                'url_transmision' => 'https://senefco.gob.bo/transmision/capacitacion',
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 6,
                'creado_por' => 1,
                'titulo' => 'Taller de Gestión de Residuos para Vecinos',
                'descripcion' => 'Capacitación ciudadana sobre separación en origen, reciclaje y manejo adecuado de residuos sólidos en el hogar.',
                'lugar' => 'Centro Vecinal Zona Sur',
                'latitud' => null,
                'longitud' => null,
                'fecha_inicio' => '2026-04-18 09:00:00',
                'fecha_fin' => '2026-04-18 12:00:00',
                'todo_el_dia' => false,
                'estado' => 'programado',
                'url_transmision' => null,
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 7,
                'creado_por' => 1,
                'titulo' => 'Feria de Empleo Municipal 2026',
                'descripcion' => 'Feria que conecta a empresas locales con jóvenes y ciudadanos en busca de trabajo. Más de 30 empresas participantes con puestos disponibles.',
                'lugar' => 'Parque Central Municipal',
                'latitud' => -16.4970,
                'longitud' => -68.1345,
                'fecha_inicio' => '2026-05-08 08:00:00',
                'fecha_fin' => '2026-05-08 17:00:00',
                'todo_el_dia' => false,
                'estado' => 'programado',
                'url_transmision' => null,
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 7,
                'creado_por' => 1,
                'titulo' => 'Feria de Salud Gratuita "Municipio Saludable"',
                'descripcion' => 'Feria de salud con servicios gratuitos de consulta médica, odontología, optometría, laboratorio y entrega de medicamentos para la ciudadanía.',
                'lugar' => 'Plaza 6 de Agosto',
                'latitud' => -16.5000,
                'longitud' => -68.1360,
                'fecha_inicio' => '2026-04-07 08:00:00',
                'fecha_fin' => '2026-04-07 16:00:00',
                'todo_el_dia' => false,
                'estado' => 'realizado',
                'url_transmision' => null,
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 8,
                'creado_por' => 1,
                'titulo' => 'Inauguración del Parque Ecológico Zona Norte',
                'descripcion' => 'Acto de inauguración del nuevo parque ecológico con áreas verdes, senderos peatonales, juegos infantiles y zona de descanso para la comunidad.',
                'lugar' => 'Zona Norte, Av. Ecológica s/n',
                'latitud' => -16.4800,
                'longitud' => -68.1280,
                'fecha_inicio' => '2026-04-25 10:00:00',
                'fecha_fin' => '2026-04-25 12:00:00',
                'todo_el_dia' => false,
                'estado' => 'programado',
                'url_transmision' => null,
                'publico' => true,
            ],
            [
                'tipo_evento_id' => 8,
                'creado_por' => 1,
                'titulo' => 'Inauguración de la Unidad Educativa Municipal "Simón Bolívar"',
                'descripcion' => 'Apertura oficial de la nueva unidad educativa con capacidad para 600 estudiantes, dotada de laboratorios, biblioteca digital y áreas deportivas.',
                'lugar' => 'Zona Centro, Calle Educación 456',
                'latitud' => -16.4965,
                'longitud' => -68.1320,
                'fecha_inicio' => '2026-02-02 09:00:00',
                'fecha_fin' => '2026-02-02 11:00:00',
                'todo_el_dia' => false,
                'estado' => 'realizado',
                'url_transmision' => null,
                'publico' => true,
            ],
        ];

        foreach ($eventos as $data) {
            $data['slug'] = Str::slug($data['titulo']);
            DB::table('eventos')->insert($data);
        }
    }
}
